  SELECT OCCUPANT_NAME,
         ROUND (SPACE_USAGE_KBYTES / 1048576, 2) AS SPACE_USAGE_MBYTES
    FROM V$SYSAUX_OCCUPANTS
ORDER BY SPACE_USAGE_KBYTES DESC;

  SELECT TASK_NAME, COUNT (*) CNT
    FROM DBA_ADVISOR_OBJECTS
GROUP BY TASK_NAME
ORDER BY CNT DESC;

SELECT name,
       ctime,
       how_created,
       OWNER_NAME
  FROM sys.wri$_adv_tasks
 WHERE name IN ('AUTO_STATS_ADVISOR_TASK', 'INDIVIDUAL_STATS_ADVISOR_TASK');

SELECT TASK_ID,
       TASK_NAME,
       EXECUTION_NAME,
       execution_start
  FROM dba_advisor_executions
 WHERE TASK_NAME = 'AUTO_STATS_ADVISOR_TASK';