SELECT TABLE_NAME AS `Table`,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)`,
  CREATE_TIME
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = ""
ORDER BY (DATA_LENGTH + INDEX_LENGTH) DESC;